### ISSUE TITLE
checkhunts throws error if hunt_sessions dir doesnt exist

### ISSUE THREAD

**Issue by JakubKwak** [LloydTao/ECM2434-Treasure-Hunt#103]

**Comment by JakubKwak** [comment]
SPEC: https://docs.google.com/document/d/19kPRwg_aBdJHBz9VsKHBIA8hwgQHC1dSZmRxJ9d3pBs/edit

**Comment by lloydtao** [comment]
Confirmed; errors are throw due to scanning the contents of directory .../hunt_sessions/ which is only created when a host is first hosted (will actually only affect the first ever user of the website).

Will fix with a simple `if (is_dir("hunt_sessions/"))` :)

**Comment by lloydtao** [comment]
Patched, check the linked PR @ https://github.com/LloydTao/ECM2434-Treasure-Hunt/pull/104 and run through the integration test in the spec
