### ISSUE TITLE
Pictures on home page don't align at certain sizes

### ISSUE THREAD

**Issue by Joseph-Lintern** [LloydTao/ECM2434-Treasure-Hunt#95]

**Comment by lloydtao** [comment]
Working on it 😋

**Comment by lloydtao** [comment]
Working on at https://github.com/LloydTao/ECM2434-Treasure-Hunt/tree/fix-index-image-align

**Comment by Joseph-Lintern** [comment]
https://docs.google.com/document/d/1BqNQuMKSfs6kLmcTRZkxxU4YfsQuDOWNG62G7D6r4DA/edit?usp=sharing

**Comment by lloydtao** [comment]
PR at https://github.com/LloydTao/ECM2434-Treasure-Hunt/pull/96
